"""empty message

Revision ID: 066b0c655f7b
Revises: 40a299b4e038
Create Date: 2025-04-06 17:23:06.585150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066b0c655f7b'
down_revision = '40a299b4e038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_balance', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('rent', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rent')
        batch_op.drop_column('account_balance')

    op.drop_table('account_log')
    # ### end Alembic commands ###
